<template>
  <div class="sector-component">
    <!-- Mostrar los tramites
     correspondientes al sector seleccionado -->
    <header>
      <h1 class="tituloPrincipal">
        {{ this.$route.params.sectorTitle }}
      </h1>
    </header>

    <div v-if="msj" class="sinTramites">
      <h2>No hay trámites para esta categoría por el momento</h2>
    </div>
    <div class="tramites">
      <div
        v-for="tramite in tramitesApi"
        :key="tramite.id"
        class="cardTramites"
      >
        <div class="divTitleImag">
          <img src="@/assets/tramite-logo.svg" :alt="tramite.id" />
          <div class="divTitle">
            <h2 class="fontB">
              {{ tramite.title }}
            </h2>
            <h3 class="mouse" @click="verRequisitos(tramite.id)">
              Ver Requisitos
            </h3>
          </div>
          <div
            v-if="this.modal === true && this.id == tramite.id"
            :id="key"
            class="modalDescription"
          >
            <div class="modalTop">
              <p @click="close">X</p>
            </div>
            <h3>{{ tramite.description }}</h3>
          </div>
        </div>

        <div class="footercard">
          <!--SI TIENE EL NIVEL REQUERIDO PUEDE HACER EL TRAMITE-->
          <router-link
            v-if="tramite.level.level <= this.nivel"
            :to="`/formulario/${tramite.title}/${tramite.id}`"
          >
            <a>Iniciar Trámite</a>
          </router-link>
          <!--SI NO!TIENE EL NIVEL REQUERIDO NO ! PUEDE HACER EL TRAMITE-->

          <div v-else @click="ModalNivel(tramite.id)">
            <a>Iniciar Trámite</a>
          </div>
        </div>
        <!--MODAL DE NIVEL 2 DE CIDI-->

        <div
          v-if="modalNivel === true && this.id == tramite.id"
          class="modalEstado"
        >
          <div class="modal-content">
            <div class="modalTop">
              <p @click="closeModalNivel">X</p>
            </div>
            <h3>Trámite no disponible.</h3>
            <p>
              para poder realizar este trámite usted debe tener
              <strong>nivel 2</strong> en Cidi.
              <br />

              <a
                href="https://cidi.cba.gov.ar/portal-publico/acceso"
                target="blak"
                class="linkCidi"
              >
                Ver más...</a
              >
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
import axios from "axios";
import setToken from "@/middlewares/setToken";
import setTokenRelations from "@/middlewares/setTokenRelations";
import { BASE_URL } from "@/env";

export default {
  data() {
    return {
      id: null,
      title: "",
      hover: false,
      tramitesApi: [],
      msj: false,
      modal: false,
      modalNivel: false,
      nivel: localStorage.getItem("nivel"),
    };
  },
  created() {
    // get tramites para la vista sectores con el id de categoria sacado del path con vue router
    //console.log(this.$route.params);
    this.GetProcedure();
  },

  methods: {
    GetProcedure() {
      const apiClient = axios.create({
        baseURL: BASE_URL,
        withCredentials: false,
        headers: {
          "auth-header": localStorage.getItem("token"),
        },
      });
      apiClient
        .get(
          "/oficina/categories/category/procedure/" +
            this.$route.params.sectorId
        )

        .then((response) => {
          if (response.status == 200) {
            for (let i = 0; i < response.data.Procedures.length; i++) {
              this.tramitesApi.push(response.data.Procedures[i]);
            }
          }
        })
        .catch((error) => {
          // console.log(error);
          if (error.response.status === 401) {
            this.$router.push("/micuenta-update");
          }
          if (error.response.status === 500) {
            if (error.response.data.message === "Token de usuario expirado") {
              setToken();
              this.GetProcedure();
            }
            if (
              error.response.data.message === "Token de representante expirado"
            ) {
              setTokenRelations();
              this.GetProcedure();
            }
          }
        });
    },

    verRequisitos(id) {
      this.modal = true;
      this.id = id;
    },
    ModalNivel(id) {
      this.modalNivel = true;
      this.id = id;
    },
    closeModalNivel() {
      this.modalNivel = false;
    },
    close() {
      this.modal = false;
    },
    back() {
      this.$router.go(-1);
    },
  },
  computed: {},
};
</script>

<style scoped>
header {
  text-align: left;
  padding-left: 5rem;
}
.slide-top {
  -webkit-animation: slide-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: slide-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-2-10 16:41:26
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-top {
  0% {
    -webkit-transform: translateY(100px);
    transform: translateY(100px);
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }
}
@keyframes slide-top {
  0% {
    -webkit-transform: translateY(100px);
    transform: translateY(100px);
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }
}
.title {
  color: var(--blue);
  margin-left: 1rem;
}

.hover {
  position: absolute;
  bottom: 0;
  font-weight: 100;
  color: var(--text-color);
}

.requisitos img {
  width: 22px;
  margin: 0 10px;
}

.sector-component {
  width: 70vw;
  height: 100vh;
  background: var;
  border-top-left-radius: 30px;
  border-bottom-left-radius: 30px;
  padding: 10px 0;
}

.descripcion {
  display: flex;
}

.tramites {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  /* text-align: center; */
  width: 90%;
  /* justify-content: center; */
  /* align-items: center; */
  /* flex-flow: row wrap; */
  margin: auto;
  margin-top: 3rem;
  gap: 20px;
  margin-bottom: 3rem;
}
.btn-iniciar {
  width: 100%;
  border: none;
  border-radius: 10px;
  background: var(--red);
  font-size: 0.9em;
  color: var(--text-color);
  transition: all 0.5s ease;
}

.tramites a {
  /*color: var(--blue);*/
  /*font-size: 0.9em;*/
  text-decoration: none;
  color: white;
  font-size: 20px;
}
.tramites a:hover {
  transition: all 0.3s ease-in-out;
  color: black;
  /*color: var(--red);
  font-size: 0.9em;
  text-decoration: none;*/
}

.tramites input:hover {
  background: var(--blue);
  color: var(--red);
}

img {
  max-width: 50px;
}

.card {
  font-weight: bold;
  padding: 0px 10px;
  border: none;
  box-shadow: 5px 5px 12px #444;
  width: 220px;
  height: 220px;
  margin: 30px 20px;
  display: flex;
  justify-content: center;
  align-items: center;
}
.sinTramites {
  margin-top: 4rem;
  text-align: center;
  width: 100%;
}
.cardTramites {
  position: relative;
  width: 90%;
  height: 14rem;
  background-color: white;
  margin: auto;
  border-radius: 40px 40px 0px 0px;
  padding-top: 2rem;
}
.divTitleImag {
  display: flex;
  flex-direction: row;
  padding-left: 1rem;
}
.divTitle {
  text-align: left;
  margin-left: 2rem;
  width: 55%;
}
.footercard {
  position: absolute;
  background-image: linear-gradient(
    to right,
    #88ba3e,
    #75b23f,
    #62aa40,
    #4ea242,
    #399943,
    #399943,
    #399943,
    #399943,
    #4ea242,
    #62aa40,
    #75b23f,
    #88ba3e
  );
  height: 3rem;
  width: 100%;
  bottom: 0;
  padding-top: 0.5rem;
}
.mouse {
  cursor: pointer;
}
.mouse:hover {
  transition: all 0.3s ease-in-out;
  color: #88ba3e;
}
.modalDescription {
  position: absolute;
  width: 250px;
  height: 50px;
  top: 7rem;
  left: 4rem;
  background-color: white;
  border: 1px solid black;
  border-radius: 20px;
  text-align: center;
  padding-top: 0.5rem;
}
.modalTop {
  position: absolute;
  top: 5px;
  right: 10px;
  cursor: pointer;
}
.modalEstado {
  display: flex;
  flex-flow: column wrap;
  justify-content: center;
  align-items: center;
  z-index: 15;
  position: absolute;
  top: 2rem;
  right: -0.8rem;
  margin-left: auto;
  margin-right: auto;
  width: 400px; /* Need a specific value to work */
  border-radius: 10px;
  background: rgba(255, 255, 255, 0.3);
  box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
  backdrop-filter: blur(20px);
  -webkit-backdrop-filter: blur(20px);
  border-radius: 10px;
  border: 1px solid rgba(255, 255, 255, 0.18);
  border-radius: 10px;
  border: 1px solid rgba(255, 255, 255, 0.18);
}
.modal-content {
  height: 100%;
  width: 100%;
  display: flex;
  flex-flow: column wrap;
  justify-content: center;
  align-items: center;
  padding: 1rem;
}
.modal-content a {
  text-decoration: none;
  color: var(--green);
}
.modal-content a:hover {
  color: #2c6331;
}
.linkCidi {
  position: absolute;
  right: 1rem;
  bottom: 1rem;
}
</style>
